apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-deployment
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: createchat
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: createchat
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.deployment.createchat.image.repository }}:{{ .Values.deployment.createchat.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.deployment.createchat.imagePullPolicy }}
        name: createchat
        ports:
        - containerPort: 5777
        resources: {{- toYaml .Values.deployment.createchat.resources | nindent 10 }}